name = "apmcb-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "apps/web/.vercel/output/static"

[vars]
SUPABASE_URL = "https://jepitcrkicwmvzrmllpn.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://jepitcrkicwmvzrmllpn.supabase.co"
NEXT_PUBLIC_BFF_URL = "https://api.apmcb.com.br"
